version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nest_pet_postgres
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_pet_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nest_user -d nest_pet_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
